### ISSUE TITLE
ReadMe Improvement.

### ISSUE THREAD

**Issue by ipranshujain** [avinashkranjan/lifeMEDeasy#103]
**Is your feature request related to a problem? Please describe.**
Yes since your site is made with Django and React sometimes it is confusing how to setup the project.

**Describe the solution you'd like**
A simple guide for setting up the project and running it locally.

I would like to do this so please assign it to me.

**Comment by avinashkranjan** [comment]
Hey @ipranshujain This issue is already noted and assigned in #91..
