### ISSUE TITLE
Dark Mode 

### ISSUE THREAD

**Issue by kumarishalini6** [avinashkranjan/lifeMEDeasy#112]
The project should also be in dark mode .
I want to put a toggle of day or night mode in the corner . 
Can i work on this issue under GSSoC'21.

**Comment by avinashkranjan** [comment]
Sure Go Ahead @kumarishalini6

**Comment by kumarishalini6** [comment]
I have send the PR  please check it.

**Comment by subhangi2731** [comment]
please assign me this
