### ISSUE TITLE
create a startup_script.sh (django+react) and a requirements file for this project.

### ISSUE THREAD

**Issue by atharvaze** [avinashkranjan/lifeMEDeasy#113]
**Is your feature request related to a problem? Please describe.**
problem: setting up the project in local machine

**Describe the solution you'd like**
A startup shell script that will set up the project and get it running.
This will help new contributors to easily set up and start this project 

Pls assign me this issue. Im a gssoc participant

**Comment by Dhriti-Roy** [comment]
Hey there, I am GSSOC'21 participant I would like to help in this issue, I have knowledge of React Js.

**Comment by avinashkranjan** [comment]
Go Ahead @atharvaze
