### ISSUE TITLE
backend for login and signup functionality and creating database to store data. 

### ISSUE THREAD

**Issue by atharvaze** [avinashkranjan/lifeMEDeasy#114]
**Is your feature request related to a problem? Please describe.**
As of now the react frontend is static. 

**Describe the solution you'd like**
I would like to work on login and signup pages to store and retrieve user data properly from the database.

**Describe alternatives you've considered**
I have been waiting for the backend creation issue to be addressed but its taking a lot of time. Instead lets begin building the backend bit by bit. I want to build the user auth backend.

**Additional context**

**Comment by avinashkranjan** [comment]
Sure Go Ahead @atharvaze
