### ISSUE TITLE
Improvement in UI of front page 

### ISSUE THREAD

**Issue by Dhriti-Roy** [avinashkranjan/lifeMEDeasy#115]
I want to improve the UI of front page and add a new option for "covid-testing" option for patients who want to go for covid testing.

**Comment by avinashkranjan** [comment]
Sure Go Ahead @Dhriti-Roy

**Comment by Dhriti-Roy** [comment]
![n](https://user-images.githubusercontent.com/74097309/114501364-7d13e900-9c47-11eb-8d83-ad2b61c88d96.jpg)

**Comment by Dhriti-Roy** [comment]
These are few changes I have done till now. Is it okay ?

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by Dhriti-Roy** [comment]
This is wrong

**Comment by Dhriti-Roy** [comment]
Atleast you should tell me whether what type of changes I have to do to make it merge in your project

**Comment by Dhriti-Roy** [comment]
You have assigned me to this project, so it's your responsibility to not leave me on a stand by ..... I am asking for help from the maintainer to kindly look upon this issue

**Comment by Dhriti-Roy** [comment]
I have waited for many weeks and now I need to know whether you are going to merge it or not, becoz you approved it previously when I showed you the demo. And now, you are not even responding.
