### ISSUE TITLE
Enable Lint Checks in Github Actions

### ISSUE THREAD

**Issue by PuneetPunamiya** [avinashkranjan/lifeMEDeasy#125]
Since we have eslint and preetier configured now, should we add lint checks in Github Actions so that lint will be checked when a pr is raised and reviewer will not have to do it manually since Github Actions will already do it

**Comment by PuneetPunamiya** [comment]
@avinashkranjan  Can I work on this issue ?

**Comment by avinashkranjan** [comment]
Sure Go Ahead @PuneetPunamiya
