### ISSUE TITLE
QA : Need of code linter and Formatter

### ISSUE THREAD

**Issue by Aryamanz29** [avinashkranjan/lifeMEDeasy#135]
- Need a workflow that ensures every contributor should follow the [PEP-8](https://www.python.org/dev/peps/pep-0008/) style guide for python code.
- We can use `flake8` for linting and `Black` for formatting source code.
- Also this workflow runs on every PR which ensures the code follows  [PEP-8](https://www.python.org/dev/peps/pep-0008/) standard or not.

**Comment by Aryamanz29** [comment]
@chetan-rns  @Aasthajain123  I would like to work on this

**Comment by avinashkranjan** [comment]
Go Ahead @Aryamanz29

**Comment by Aryamanz29** [comment]
@chetan-rns  @avinashkranjan  Please review this PR
