### ISSUE TITLE
Auto merge PR from dependabot

### ISSUE THREAD

**Issue by Ankita297** [avinashkranjan/lifeMEDeasy#137]
**Is your feature request related to a problem? Please describe.**
github action to Auto merge PR from dependabot

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![done by Ankita297 · Pull Request #5 · Ankita297_Story - Google Chrome 17-04-2021 20_05_45](https://user-images.githubusercontent.com/67833077/115946312-03e58300-a4de-11eb-94f6-1cde0ea821c6.png)

**Comment by avinashkranjan** [comment]
Go Ahead @Ankita297
