### ISSUE TITLE
Social media icons

### ISSUE THREAD

**Issue by kumarishalini6** [avinashkranjan/lifeMEDeasy#147]
**Describe the bug**
I have seen that their is no social media icons present in this project.

**To Reproduce**
I want to add social media icons with hover effect at the home page 

![Opportunity Calendar - Personal - Microsoft​ Edge 5_14_2021 05_11_05 PM](https://user-images.githubusercontent.com/69043944/118266222-c03fc280-b466-11eb-8f4c-bc2327c6c2d8.png)

**Comment by chetan-rns** [comment]
@kumarishalini6 Why do we need social media icons? I don't think we have accounts for these links to point

**Comment by kumarishalini6** [comment]
Oo I am so sorry actually I want to create this issue on other projects
