### ISSUE TITLE
Fix Navbar Position

### ISSUE THREAD

**Issue by Saatvik21** [avinashkranjan/lifeMEDeasy#149]
**Is your feature request related to a problem? Please describe.**
Currently, the navbar is not sticky/fixed, and a person who has to go to another page of the website has to scroll up to see the navbar.

**Describe the solution you'd like**
I would like to make the navbar sticky.

**Describe alternatives you've considered**
`N/A`

**Comment by chetan-rns** [comment]
Please go ahead @Saatvik21
