### ISSUE TITLE
Login with Google button

### ISSUE THREAD

**Issue by kumarishalini6** [avinashkranjan/lifeMEDeasy#151]
**Is your feature request related to a problem? Please describe.**
There should be option of login with google button in every registration page

**Describe the solution you'd like**
I would like to design this button in every page.
 can I work  on this issue under GSSoC'21

**Comment by chetan-rns** [comment]
Sure @kumarishalini6

**Comment by subhangi2731** [comment]
@chetan-rns @avinashkranjan please assign me this

**Comment by kumarishalini6** [comment]
Sorry to say but this issue is already assigned to me
