### ISSUE TITLE
Custom Scrollbar

### ISSUE THREAD

**Issue by Saatvik21** [avinashkranjan/lifeMEDeasy#153]
**Is your feature request related to a problem? Please describe.**
The current scrollbar does not match the color/theme of the website.

**Describe the solution you'd like**

I would like to make a custom scrollbar that will match the color of the navbar

**Additional context**
![Screenshot_1](https://user-images.githubusercontent.com/61618767/118354030-b7461280-b586-11eb-98bc-d3163df4d341.png)

Kindly assign me this issue under GSSoC'21

**Comment by avinashkranjan** [comment]
Sure Go Ahead @Saatvik21
