### ISSUE TITLE
Frontend: Complete the let's talk section by creating a chatbot

### ISSUE THREAD

**Issue by Arnab9674** [avinashkranjan/lifeMEDeasy#16]
I want to use react-chatbot-kit module to complete it

**Comment by avinashkranjan** [comment]
- Follow the Colour scheme of the website

- Images Used are from Undraw 

- If any Anthing..Contact the Mentor.

Assigning it to you..Go On..

**Comment by aqua0** [comment]
I can make a chatbot using python (rasa) for this can you assign this to me please.
will try my best.

**Comment by avinashkranjan** [comment]
Go Ahead @aqua0

**Comment by rk05-lenavo** [comment]
I'm the participate of GSSOC'21 please assign me this issue

**Comment by avinashkranjan** [comment]
Go Ahead @rk05-lenavo

**Comment by aqua0** [comment]
Hi @avinashkranjan  please don't unassign me I am working on it still. I had learn rasa before I could do it. That's why it took some time.
Please reassign me.

**Comment by avinashkranjan** [comment]
Hey @aqua0 Keep Updating the mentors about the progress, if any doubts contact them..Reassigning it you

**Comment by subhangi2731** [comment]
@avinashkranjan @chetan-rns please assign me this I want to work

**Comment by avinashkranjan** [comment]
Go Ahead @subhangi2731

**Comment by kumarishalini6** [comment]
@avinashkranjan  if no one is working on this issue can i

**Comment by avinashkranjan** [comment]
Go Ahead @kumarishalini6 even if you're not done with the complete implementation..Make a PR before 12 and then work on that PR..

**Comment by kumarishalini6** [comment]
Ok thanks
