### ISSUE TITLE
Redesign homepage

### ISSUE THREAD

**Issue by kumarishalini6** [avinashkranjan/lifeMEDeasy#172]
The home page is too simple , I want to make make page intresting by changing the images style of button at the home page .
Can I work on this issue under GSSoC'21 participant.
@chetan-rns  please assign this issue to me

**Comment by avinashkranjan** [comment]
Hey @kumarishalini6 Kindly Show a prototype before you start working on this..

**Comment by kumarishalini6** [comment]
Actually because of latest upstream there is a lots of bugs in project may be it is in my side 
I was thinking to fork it again then I will send you

**Comment by kumarishalini6** [comment]
Now the header file is not visible 
![lifeMEDeasy - Personal - Microsoft​ Edge 5_26_2021 07_38_48 AM](https://user-images.githubusercontent.com/69043944/119592203-7dde8580-bd84-11eb-905f-eec7296e88b1.png)

**Comment by kumarishalini6** [comment]
can I fixed this issue and design it again??

**Comment by avinashkranjan** [comment]
Go Ahead @kumarishalini6
