### ISSUE TITLE
Navbar 

### ISSUE THREAD

**Issue by kumarishalini6** [avinashkranjan/lifeMEDeasy#173]
Because of navbar the cards are not properly visible , I was thinking to make a side navbar because there is mix up on that navbar.can I work on this issue under GSSoC'21 participant

**Comment by kumarishalini6** [comment]
Because of so many links in the navbar it is not looking nice and hover effect is not in every links that's why I want to create a side navbar . can i work on this issue??

**Comment by avinashkranjan** [comment]
Don't Create a Sidenav...Clean and redesign the existing navbar..Make the text a little smaller and move few elements in nested menu such as covid .. change sign in/sign up to login..

**Comment by kumarishalini6** [comment]
Ok
