### ISSUE TITLE
Custom alert

### ISSUE THREAD

**Issue by ChitvanRamani22** [avinashkranjan/lifeMEDeasy#176]
I would like to add a custom alert box just below the navbar saying something like. "Great Landing! Login to continue.". Will provide functionality that it will appear for only 4 seconds and then will disappear.
@Aasthajain123 @chetan-rns please assign this to me. Thankyou!

**Comment by avinashkranjan** [comment]
It's not needed for this project..It would hamper User Experience as we already have a landing Page of the website..we don't need another custom alert notifying the same
