### ISSUE TITLE
Fix the footer to the bottom of the page

### ISSUE THREAD

**Issue by chetan-rns** [avinashkranjan/lifeMEDeasy#181]
**Describe the bug**

The footer bar is not fixed properly and is floating on every page

**Expected behavior**
The footer should be fixed to the bottom of the page

**Screenshots**
![Screenshot from 2021-05-27 10-42-40](https://user-images.githubusercontent.com/21128732/119769560-4a147480-bed8-11eb-9c1c-ff7f9733f2fe.png)

**Comment by kumarishalini6** [comment]
Are you working on this issue??

**Comment by kumarishalini6** [comment]
If not then assign this issue to me.

**Comment by avinashkranjan** [comment]
Go Ahead @kumarishalini6
