### ISSUE TITLE
Adding Map Feature to Call an Ambulance Page

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/lifeMEDeasy#20]
# AIM

- Adding map Feature to Call an Ambulance

# Details

- Adding Live Location Features, Library which can be used are for eg: `react-map-gl', 'google-map-react`
- You are allowed the explore any library you want to

**Comment by Arnab9674** [comment]
Can i do it??

**Comment by avinashkranjan** [comment]
Ya Sure..Assigned to you..

**Comment by akashakara** [comment]
Do reply if u need any more features

**Comment by garvitgupta13** [comment]
> # AIM
> * Adding map Feature to Call an Ambulance
> 
> # Details
> * Adding Live Location Features, Library which can be used are for eg: `react-map-gl', 'google-map-react`
> * You are allowed the explore any library you want to

Hey @avinashkranjan please describe the feature you want a bit more. I guess I can do it with `google-map-react` . 
Which objects live location you want on map and how to get its coordinates?
Where you want the map to be displayed?

**Comment by garvitgupta13** [comment]
Hey @avinashkranjan please let me know if this issue is still open?

**Comment by avinashkranjan** [comment]
Hey @garvitgupta13 This is a complex Issue..So, 

# Aim
- Create an UI like Uber but for Ambulance

# Feature Details
- A Map Locating your current position
- A Dialog box to find any address
- Distance Calculator Between the two locations

Once this is done we can go forward with  other features.

**Comment by lopeselio** [comment]
Is this an open issue? Can I start working on this?

**Comment by avinashkranjan** [comment]
Sure Go Ahead @lopeselio

**Comment by atharvaze** [comment]
can I work on this issue @avinashkranjan?

**Comment by avinashkranjan** [comment]
Sure Go Ahead @atharvaze

**Comment by subhangi2731** [comment]
@avinashkranjan @chetan-rns please assign me this I want to work

**Comment by avinashkranjan** [comment]
Go Ahead @subhangi2731

**Comment by subhangi2731** [comment]
@avinashkranjan the requirements.txt file is not there can u guide me how should I proceed??

**Comment by kumarishalini6** [comment]
@avinashkranjan can i work on this issue

**Comment by kumarishalini6** [comment]
@avinashkranjan  sorry to say but I am going to send PR on this issue you can assign me when ever you are free but I have not that much time. sorry once again.

**Comment by avinashkranjan** [comment]
> @avinashkranjan sorry to say but I am going to send PR on this issue you can assign me when ever you are free but I have not that much time. sorry once again.

I already told you on discord to start working on the Issue and create a PR..don't wait for me to assign you as it is the last day..and I'm still busy..
