### ISSUE TITLE
Building Backend of the Website

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/lifeMEDeasy#27]
#AIM

-  Building Backend of the Website

# Details

- Linking all the pages
- Adding Database to the backend

**Comment by Arnab9674** [comment]
can i do it??

**Comment by avinashkranjan** [comment]
@Arnab9674 Sure.... Assigned to you..

**Comment by rk05-lenavo** [comment]
I'm a participant in GSSOC'21 .Can you please assign me this?

**Comment by avinashkranjan** [comment]
Hey @rk05-lenavo The backend is in Django, Kindly go ahead..

**Comment by rk05-lenavo** [comment]
@avinashkranjan  Thanks for assigning.

**Comment by 4doctorstrange** [comment]
Hello there, I am a GSSoC'21 participant. I would love to work on the backend and add a database. I  have developed projects using Django Framework, some of them are deployed on the Heroku server (you can have a look at them on my profile (BlogApp, URL shortener))

**Comment by chetan-rns** [comment]
Hi @rk05-lenavo, please let me know if you need any help with the issue :)

**Comment by rk05-lenavo** [comment]
@chetan-rns  Yes sir working on it.

**Comment by SnehaVeerakumar** [comment]
I have a good knowledge about django to help in this issue. As a part of GSSOC'21 I would like to work on this project. Kindly let me know for any help.

**Comment by avinashkranjan** [comment]
Hey @rk05-lenavo Kindly Keep Updating the mentors, about the progress..It's been almost 3 weeks.

**Comment by atharvaze** [comment]
is the backend work done? can i help in this issue?

**Comment by atharvaze** [comment]
is the backend work done? Can I help with this issue as part of GSSOC 21?

**Comment by avinashkranjan** [comment]
Since, There's no Update Assigning the Issue to @atharvaze , Go Ahead
