### ISSUE TITLE
Update project name in greeting message

### ISSUE THREAD

**Issue by chetan-rns** [avinashkranjan/lifeMEDeasy#66]
**Describe the bug**
The project name in the greeting message sent by the GitHub action should be corrected.

**To Reproduce**
Check the greeting message posted by Github action

```shell
        issue-message: 'Hi thanks for creating your first issue at Amazing-Python-Scripts, hope you followed the guidelines.'
        pr-message: 'Congratulations!! for making your first PR at  Amazing-Python-Scripts, our mentors will review it soon.'
 ```

**Comment by rk05-lenavo** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Comment by rk05-lenavo** [comment]
@avinashkranjan Can you please assign me this?

**Comment by avinashkranjan** [comment]
We already have received an PR for this. Kindly look for other issues..
