### ISSUE TITLE
Adding Contributor section in readme  ( Automatically )

### ISSUE THREAD

**Issue by rohank2502** [avinashkranjan/lifeMEDeasy#70]
I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigend !!

**Comment by chetan-rns** [comment]
Hi @rohank2502, GitHub already displays a contributor's list on the project home page(https://github.com/avinashkranjan/lifeMEDeasy/graphs/contributors). Are you suggesting something similar. I wonder why we need a separate list on the README

**Comment by avinashkranjan** [comment]
We already have that @rohank2502, Kindly look for other open Issues
