### ISSUE TITLE
Improving chatbot functionalities

### ISSUE THREAD

**Issue by codeshruti** [avinashkranjan/lifeMEDeasy#73]
Adding more features to the chatbot. I am a GSSOC'21 participant.

**Comment by avinashkranjan** [comment]
Go Ahead @codeshruti

**Comment by avishmehta68710** [comment]
can i work on this issue under GSSOC 2021

**Comment by avinashkranjan** [comment]
Hey @avishmehta68710 , @codeshruti is working on this issue you can help her with more functionalities and I'll score you both as per your contribution
