### ISSUE TITLE
[Feat]: Lazy Loading Component to increase performance of Website

### ISSUE THREAD

**Issue by WaderManasi** [avinashkranjan/lifeMEDeasy#75]
**Is your feature request related to a problem? Please describe.**
Inorder to reduce the initial loading time of website, lazy loading can be implemented.

**Describe the solution you'd like**
Render the components only when the user requests for it.
(initial loading time will get reduced)
Also, we can add styled react loaders .

I wish to contribute on this, being part of gssoc'21.

**Comment by avinashkranjan** [comment]
Sure Go Ahead @WaderManasi
