### ISSUE TITLE
CONTRIBUTING.md file not rendering as markdown

### ISSUE THREAD

**Issue by WaderManasi** [avinashkranjan/lifeMEDeasy#80]
**Describe the bug**
In CONTRIBUTING.md file, markdown is not being rendered, hence entire content is displayed as simple plain text.

**To Reproduce**
Adding correct markdown syntax to resolve this issue.

**Screenshots**
All markdown syntax is displayed.
![mis](https://user-images.githubusercontent.com/52437677/111795649-69e25780-88ed-11eb-90a1-9629eb3718b9.PNG)

**Additional context**
I would like to work on this issue being part of gssoc'21.

**Comment by avinashkranjan** [comment]
Go ahead @WaderManasi
