### ISSUE TITLE
Add instructions to run the project locally

### ISSUE THREAD

**Issue by chetan-rns** [avinashkranjan/lifeMEDeasy#91]
**Is your feature request related to a problem? Please describe.**
Add step-by-step instructions to run the project on the developer's local machine. Add details about the prerequisites that should be installed before running the project.

**Describe the solution you'd like**
I would like to see the following points documented
1. Prerequisites to install
2. Commands to run the project

We could consider adding a Makefile and a Dockerfile in the same issue. But we should start with something simple for now.

**Comment by GurshehzadSingh** [comment]
im a gssoc participant and i would like to work on this isuue.

**Comment by subhasmitapradhan** [comment]
hello sir, I am a gssoc participant, kindly assign this issue to me.

**Comment by avinashkranjan** [comment]
Hey @GurshehzadSingh Go Ahead

**Comment by GurshehzadSingh** [comment]
Im just submitting this in few hours

**Comment by avinashkranjan** [comment]
It's been a day @GurshehzadSingh ..

**Comment by GurshehzadSingh** [comment]
Facing some doubts and issues. Shall i ping you on discord?

**Comment by avinashkranjan** [comment]
Yes..

**Comment by salonidabgar** [comment]
Hi! I want to work on this issue as a GSSOC'21 participant.
