### ISSUE TITLE
Fix eslint warnings

### ISSUE THREAD

**Issue by chetan-rns** [avinashkranjan/lifeMEDeasy#93]
**Describe the bug**
Frontend code has eslint warnings

![Screenshot from 2021-03-26 22-13-32](https://user-images.githubusercontent.com/21128732/112664981-8f88d700-8e80-11eb-8e20-643db8249d90.png)

**To Reproduce**
1. After cloning the repository
2. Install packages `npm i`
3. Start the server `npm start`
4. Observe `eslint` warnings in the log

**Expected behavior**
All eslint warnings must be fixed

**Comment by A-HK** [comment]
Hey! I think I can work on this.
Would you be willing to assign it to me under GSSoc'21?

**Comment by chetan-rns** [comment]
Sure @A-HK, please go ahead :)

**Comment by A-HK** [comment]
Hey @chetan-rns , does this log look fine to you?
![terminal_img](https://user-images.githubusercontent.com/73497800/112675261-f2806b00-8e8c-11eb-9e56-31f8520f8fcb.png)

If it does, let me know if I should make a PR !

**Comment by A-HK** [comment]
Hey @chetan-rns @avinashkranjan , made a PR for the same. Please check if everything is satisfactory whenever you're free!
