### ISSUE TITLE
Add GitHub action to check code quality 

### ISSUE THREAD

**Issue by chetan-rns** [avinashkranjan/lifeMEDeasy#94]
**Is your feature request related to a problem? Please describe.**

Currently, GitHub workflows don't check if the code in the PRs is syntactically correct. 

**Describe the solution you'd like**

Add a GitHub action that can determine the code quality of the code and fail if it doesn't meet the requirements.

**Comment by DineshKoushik** [comment]
@chetan-rns Hi again, Maybe I'll try to add this action along with the footer? Is that fine?

**Comment by kcoder63** [comment]
Github actions are needed to be added by the maintainers only, participants don't have access

**Comment by DineshKoushik** [comment]
Oh Thanks for that @kcoder63 , I didn't know this.

**Comment by palsumit99** [comment]
@avinashkranjan please assign this issue to me i want to add this feature to the project.
