### ISSUE TITLE
Fix footer to the bottom of the page

### ISSUE THREAD

**Issue by chetan-rns** [avinashkranjan/lifeMEDeasy#95]
**Describe the bug**
Footer doesn't stick to the bottom of the page

**To Reproduce**
1. Run the server `npm start`
2. Observe the footer in the center

![Screenshot from 2021-03-26 22-43-30](https://user-images.githubusercontent.com/21128732/112668691-ceb92700-8e84-11eb-8d47-ca68682b9a32.png)

**Expected behavior**
Create a fixed footer that sticks to the bottom of the page.

**Comment by DineshKoushik** [comment]
Hi @chetan-rns , I will give this a try.

**Comment by chetan-rns** [comment]
Thanks @DineshKoushik, will assign it to you :)

**Comment by Kavs-123** [comment]
hey @DineshKoushik can u please assign me this issue..i want to give it a try and go ahead with the same

**Comment by DineshKoushik** [comment]
@Kavs-123 Hello, first of all, I'm not admin for this project and second, I already resolved this issue.
