### ISSUE TITLE
Configure eslint and prettier for the UI application 

### ISSUE THREAD

**Issue by PuneetPunamiya** [avinashkranjan/lifeMEDeasy#97]
Configure eslint and prettier for the UI application 

- The UI application should have a lint and prettier configuration which will
keep the code in one format (for e.g. proper spacing, etc) and will make 
the code look preetier as well

 - Configuring `eslint` and `preetier`  and executing the commands like 
 `npm run lint` and `npx prettier --write .`  will give the warnings/errors
  which the developers can fix before the code is submitted

**Comment by PuneetPunamiya** [comment]
Hey, @avinashkranjan 
I'm the participant of GSSOC'21 could you please assign me this issue

**Comment by PuneetPunamiya** [comment]
@avinashkranjan  would you mind if I also submit a patch which fixes the lint errors after this pr get's merged https://github.com/avinashkranjan/lifeMEDeasy/issues/97

**Comment by avinashkranjan** [comment]
Sure Go Ahead @PuneetPunamiya

**Comment by avinashkranjan** [comment]
Mention This fix for this Issue for the new PR..So, you won't have to create a new Issue
